owner: integratedmodelling
repo: upptime

sites:
  - name: Hub
    url: https://intedmodelling.org/hub/
  - name: k.Explorer
    url: https://integratedmodelling.org/modeler/
  - name: Data
    url: https://data.integratedmodelling.org/

assignees:
  - euskalhenriko

status-website:
  baseUrl: /repo
  name: Integrated Modelling
