owner: integratedmodelling
repo: upptime

sites:
  - name: Hub
    url: https://integratedmodelling.org/hub/
  - name: Confluence
    url: https://confluence.integratedmodelling.org/
  - name: Chat
    url: https://chat.integratedmodelling.org/
  - name: Web
    url: https://klab.integratedmodelling.org/
  - name: CKAN
    url: https://data.integratedmodelling.org/

assignees:
  - euskalhenriko

status-website:
  cname: status.integratedmodelling.org
  name: Integrated Modelling
